version: "3.9"
services:
  logship-database:
    container_name: "logship-database"
    image: ghcr.io/logship-io/logship-database:latest
    # network_mode: host
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./config/logship-database/appsettings.json:/app/appsettings.json:ro
      - ./logship:/logship:rw
  logship-agent:
    container_name: "logship-agent"
    image: ghcr.io/logship-io/logship-agent:latest
    # network_mode: host
    restart: always
    volumes:
      - ./config/logship-agent/appsettings.json:/app/appsettings.json:ro
    ports:
      - 49999:49999
    depends_on:
      logship-database:
        condition: service_started
  logship-frontend:
    container_name: "logship-frontend"
    image: ghcr.io/logship-io/logship-frontend:latest
    restart: always
    # network_mode: host
    ports:
      - 8000:8000
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./config/logship-frontend/appsettings.json:/app/appsettings.json:ro


